# Generated by Django 3.2.7 on 2021-10-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='MobileNumber',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
