# Generated by Django 3.2.7 on 2021-10-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRS', '0002_auto_20211023_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
    ]
