# Generated by Django 3.2.7 on 2021-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRS', '0003_auto_20211023_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='anonymous.jpeg', upload_to='profile_pics'),
        ),
    ]
